"""v0.3.0 initial schema

Revision ID: 0001_v0_3_0
Revises:
Create Date: 2026-07-14 09:34:30.089289
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0001_v0_3_0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('singleton_key', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('singleton_key', name=op.f('uq_admins_singleton_key')),
    sa.UniqueConstraint('username', name=op.f('uq_admins_username'))
    )
    op.create_table('api_clients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('allowed_event_types', sa.JSON(), nullable=False),
    sa.Column('allowed_recipient_ids', sa.JSON(), nullable=False),
    sa.Column('allow_broadcast', sa.Boolean(), nullable=False),
    sa.Column('allow_critical', sa.Boolean(), nullable=False),
    sa.Column('allow_media', sa.Boolean(), nullable=False),
    sa.Column('allow_voice', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_clients')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_clients_key_hash')),
    sa.UniqueConstraint('key_prefix', name=op.f('uq_api_clients_key_prefix'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('events',
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ignore_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('source_type', 'source_id', 'event_key', name='uq_event_source_key')
    )
    op.create_index('ix_events_accepted_at', 'events', ['accepted_at'], unique=False)
    op.create_table('incoming_messages',
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('sender_external_id', sa.String(length=128), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_refs', sa.JSON(), nullable=False),
    sa.Column('event_payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incoming_messages')),
    sa.UniqueConstraint('channel', 'dedupe_key', name='uq_incoming_message_dedupe')
    )
    op.create_index('ix_incoming_processing', 'incoming_messages', ['processing_status', 'received_at'], unique=False)
    op.create_table('media_assets',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_media_id', sa.String(length=256), nullable=True),
    sa.Column('provider_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_media_assets_storage_path'))
    )
    op.create_index('ix_media_assets_checksum', 'media_assets', ['checksum_sha256'], unique=False)
    op.create_index('ix_media_assets_expires_at', 'media_assets', ['expires_at'], unique=False)
    op.create_table('people',
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_table('plugin_configs',
    sa.Column('plugin_id', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plugin_id', name=op.f('pk_plugin_configs'))
    )
    op.create_table('plugin_runs',
    sa.Column('plugin_id', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('emitted_event_count', sa.Integer(), nullable=False),
    sa.Column('cursor_before', sa.JSON(), nullable=True),
    sa.Column('cursor_after', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_runs'))
    )
    op.create_index('ix_plugin_runs_history', 'plugin_runs', ['plugin_id', 'started_at'], unique=False)
    op.create_index('ix_plugin_runs_queue', 'plugin_runs', ['status', 'created_at'], unique=False)
    op.create_table('plugin_states',
    sa.Column('plugin_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plugin_id', 'key', name=op.f('pk_plugin_states'))
    )
    op.create_table('plugins',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('install_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_open', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugins'))
    )
    op.create_index('ix_plugins_schedule', 'plugins', ['enabled', 'next_run_at'], unique=False)
    op.create_table('secrets',
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('scope_type', 'scope_id', 'name', name='uq_secret_scope')
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_platform_settings'))
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('worker_type', sa.String(length=50), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_table('notifications',
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('reminder_id', sa.String(length=64), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('media_asset_id', sa.String(length=64), nullable=True),
    sa.Column('ack_policy', sa.String(length=10), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('require_ack', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifications_event_id_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('refresh_sessions',
    sa.Column('admin_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_refresh_sessions_admin_id_admins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash'))
    )
    op.create_table('reminders',
    sa.Column('creator_person_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('require_ack', sa.Boolean(), nullable=False),
    sa.Column('ack_policy', sa.String(length=10), nullable=False),
    sa.Column('repeat_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('max_reminders', sa.Integer(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['creator_person_id'], ['people.id'], name=op.f('fk_reminders_creator_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index('ix_reminders_due', 'reminders', ['status', 'next_run_at'], unique=False)
    op.create_table('wecom_identities',
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_wecom_identities_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wecom_identities')),
    sa.UniqueConstraint('user_id', name=op.f('uq_wecom_identities_user_id'))
    )
    op.create_table('conversation_sessions',
    sa.Column('wecom_identity_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['wecom_identity_id'], ['wecom_identities.id'], name=op.f('fk_conversation_sessions_wecom_identity_id_wecom_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions')),
    sa.UniqueConstraint('wecom_identity_id', name=op.f('uq_conversation_sessions_wecom_identity_id'))
    )
    op.create_table('deliveries',
    sa.Column('notification_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.String(length=500), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('notification_id', 'channel', 'recipient_type', 'recipient_id', name='uq_delivery_target')
    )
    op.create_index('ix_deliveries_queue', 'deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_table('reminder_recipients',
    sa.Column('reminder_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_reminder_recipients_person_id_people')),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_reminder_recipients_reminder_id_reminders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_recipients')),
    sa.UniqueConstraint('reminder_id', 'person_id', name='uq_reminder_recipient')
    )
    op.create_table('delivery_attempts',
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('provider_status', sa.Integer(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_delivery_attempts_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_attempts')),
    sa.UniqueConstraint('delivery_id', 'attempt_no', name='uq_attempt_number')
    )
    op.create_table('notification_actions',
    sa.Column('reminder_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=False),
    sa.Column('notification_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_actions_notification_id_notifications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['reminder_recipients.id'], name=op.f('fk_notification_actions_recipient_id_reminder_recipients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_notification_actions_reminder_id_reminders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_actions')),
    sa.UniqueConstraint('token_hash', name='uq_notification_action_token_hash')
    )
    op.create_index('ix_notification_actions_reminder', 'notification_actions', ['reminder_id', 'recipient_id'], unique=False)
    op.create_table('interaction_events',
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('sender_external_id', sa.String(length=128), nullable=False),
    sa.Column('notification_action_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('response_code', sa.String(length=500), nullable=True),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['notification_action_id'], ['notification_actions.id'], name=op.f('fk_interaction_events_notification_action_id_notification_actions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_events')),
    sa.UniqueConstraint('channel', 'dedupe_key', name='uq_interaction_event_dedupe')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction_events')
    op.drop_index('ix_notification_actions_reminder', table_name='notification_actions')
    op.drop_table('notification_actions')
    op.drop_table('delivery_attempts')
    op.drop_table('reminder_recipients')
    op.drop_index('ix_deliveries_queue', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('conversation_sessions')
    op.drop_table('wecom_identities')
    op.drop_index('ix_reminders_due', table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('refresh_sessions')
    op.drop_table('notifications')
    op.drop_table('worker_heartbeats')
    op.drop_table('platform_settings')
    op.drop_table('secrets')
    op.drop_index('ix_plugins_schedule', table_name='plugins')
    op.drop_table('plugins')
    op.drop_table('plugin_states')
    op.drop_index('ix_plugin_runs_queue', table_name='plugin_runs')
    op.drop_index('ix_plugin_runs_history', table_name='plugin_runs')
    op.drop_table('plugin_runs')
    op.drop_table('plugin_configs')
    op.drop_table('people')
    op.drop_index('ix_media_assets_expires_at', table_name='media_assets')
    op.drop_index('ix_media_assets_checksum', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_incoming_processing', table_name='incoming_messages')
    op.drop_table('incoming_messages')
    op.drop_index('ix_events_accepted_at', table_name='events')
    op.drop_table('events')
    op.drop_table('audit_logs')
    op.drop_table('api_clients')
    op.drop_table('admins')
    # ### end Alembic commands ###
