"""add_reminder_occurrence

Revision ID: 0007_add_reminder_occurrence
Revises: 0006_v0_7_0
Create Date: 2026-07-16 12:33:40.163964
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007_add_reminder_occurrence"
down_revision: str | None = "0006_v0_7_0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder_occurrences",
        sa.Column("reminder_id", sa.String(length=64), nullable=False),
        sa.Column("occurrence_key", sa.String(length=200), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("title_snapshot", sa.String(length=200), nullable=False),
        sa.Column("content_snapshot", sa.Text(), nullable=False),
        sa.Column("content_type_snapshot", sa.String(length=20), nullable=False),
        sa.Column("media_asset_id_snapshot", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("ack_policy_snapshot", sa.String(length=10), nullable=False),
        sa.Column("repeat_interval_seconds_snapshot", sa.Integer(), nullable=True),
        sa.Column("max_reminders_snapshot", sa.Integer(), nullable=True),
        sa.Column("stop_at_snapshot", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
            name=op.f("fk_reminder_occurrences_reminder_id_reminders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_occurrences")),
        sa.UniqueConstraint("reminder_id", "occurrence_key", name="uq_reminder_occurrence_key"),
    )
    op.create_index(
        "ix_reminder_occurrences_due",
        "reminder_occurrences",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "reminder_occurrence_recipients",
        sa.Column("occurrence_id", sa.String(length=64), nullable=False),
        sa.Column("person_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notify_count", sa.Integer(), nullable=False),
        sa.Column("next_notify_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["reminder_occurrences.id"],
            name=op.f("fk_reminder_occurrence_recipients_occurrence_id_reminder_occurrences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_reminder_occurrence_recipients_person_id_people"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_occurrence_recipients")),
        sa.UniqueConstraint("occurrence_id", "person_id", name="uq_occurrence_recipient"),
    )
    op.create_index(
        "ix_occurrence_recipients_due",
        "reminder_occurrence_recipients",
        ["status", "next_notify_at"],
        unique=False,
    )
    with op.batch_alter_table("notification_actions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("occurrence_id", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("occurrence_recipient_id", sa.String(length=64), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_actions_occurrence_id_reminder_occurrences"),
            "reminder_occurrences",
            ["occurrence_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_notification_actions_occurrence_recipient_id_reminder_occurrence_recipients"
            ),
            "reminder_occurrence_recipients",
            ["occurrence_recipient_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reminder_occurrence_id", sa.String(length=64), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_notifications_reminder_occurrence_id_reminder_occurrences"),
            "reminder_occurrences",
            ["reminder_occurrence_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("content_type", sa.String(length=20), server_default="text", nullable=False)
        )
        batch_op.add_column(sa.Column("media_asset_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("url", sa.String(length=2048), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_reminders_media_asset_id_media_assets"),
            "media_assets",
            ["media_asset_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_reminders_media_asset_id_media_assets"), type_="foreignkey"
        )
        batch_op.drop_column("url")
        batch_op.drop_column("media_asset_id")
        batch_op.drop_column("content_type")

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_notifications_reminder_occurrence_id_reminder_occurrences"),
            type_="foreignkey",
        )
        batch_op.drop_column("reminder_occurrence_id")

    with op.batch_alter_table("notification_actions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_notification_actions_occurrence_recipient_id_reminder_occurrence_recipients"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_notification_actions_occurrence_id_reminder_occurrences"),
            type_="foreignkey",
        )
        batch_op.drop_column("occurrence_recipient_id")
        batch_op.drop_column("occurrence_id")

    op.drop_index("ix_occurrence_recipients_due", table_name="reminder_occurrence_recipients")
    op.drop_table("reminder_occurrence_recipients")
    op.drop_index("ix_reminder_occurrences_due", table_name="reminder_occurrences")
    op.drop_table("reminder_occurrences")
    # ### end Alembic commands ###
